apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  finalizers:
    - percona.com/delete-backup
  name: test-backup
  namespace: percona
spec:
  pxcCluster: percona-pxc-db
  storageName: fs-pvc
