apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  finalizers:
    - percona.com/delete-backup
  name: test-backup
  namespace: percona
spec:
  pxcCluster: percona-pxc-db-stage
  backupName: test-backup
