apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: backup-restoration
  finalizers:
    - percona.com/delete-backup
spec:
  pxcCluster: percona-pxc-db-stage
  backupName: test-backup
